# Generated by Django 5.0 on 2023-12-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_rename_products_product_rename_services_service_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
        migrations.RenameModel(
            old_name='Supplie',
            new_name='Supplies',
        ),
        migrations.RenameModel(
            old_name='SupplieItem',
            new_name='SuppliesItems',
        ),
        migrations.RenameModel(
            old_name='Types_product',
            new_name='Types_products',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
