# Generated by Django 5.0 on 2023-12-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_product_products_rename_service_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliesitems',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество'),
        ),
    ]
