# Generated by Django 5.0 on 2023-12-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_write_offs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='quantity',
        ),
    ]
