# Generated by Django 5.0 on 2023-12-18 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_sales_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filials',
            name='manager',
        ),
        migrations.AddField(
            model_name='users',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.filials', verbose_name='Филиал'),
        ),
    ]
