# Generated by Django 5.0 on 2023-12-19 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_filials_manager_users_filial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата заявки')),
                ('date_completion', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='Стоимость')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.filials', verbose_name='Филиал')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заказ на услугу',
                'verbose_name_plural': 'Заказы на услуги',
            },
        ),
    ]
