# Generated by Django 5.0 on 2023-12-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_serviceorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceOrder',
        ),
    ]
